[build]
builder = "nixpacks"

[deploy]
startCommand = "node index.js"
restartPolicyType = "always"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 30
numReplicas = 1

[environments.production]
NODE_ENV = "production"